name = "serverabiii"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

routes = [
  { pattern = "stop.serveraby.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.stop.serveraby.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.stop.serveraby.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.stop.serveraby.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.stop.serveraby.web.id", custom_domain = true },
  { pattern = "support.zoom.us.stop.serveraby.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.stop.serveraby.web.id", custom_domain = true },

[[kv_namespaces]]
binding = "SIREN"
id = "2052d9e1b5494957aa98602ad27ed692"
[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AbieXYZ/abiiigitme/refs/heads/master/web/index.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AbieXYZ/abiiigitme/refs/heads/master/web/link.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AbieXYZ/abiiigitme/refs/heads/master/web/sub.html"
